### ISSUE TITLE
yaml examples in the manpage seem to be incorrect

### ISSUE THREAD

**Issue by bcl** [daethnir/authprogs#3]
I couldn't get a single example I tried to parse correctly. It ended up that the config.yaml file from the test was the most useful for figuring out the correct formatting.

Tested using:
PyYAML-3.10-11.el7.x86_64
libyaml-0.1.4-10.el7.x86_64

eg. this example results in a parse error:

    --
    from: 192.168.1.5
    --
    from: [192.168.0.1, 10.0.0.3]
    --
    from:
        - 192.168.0.1
        - 10.10.0.3

**Comment by daethnir** [comment]
Fixed in today's push. Not sure how I lost all those important leading spaces.

Did some cleanup of both the documentation and added some debugging output to help find issues when it's parsing the configs.
